name: Check-Update

on:
  schedule:
    # Runs twice a day.
    - cron: 0 3 * * *
    - cron: 0 15 * * *
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: check-update
  cancel-in-progress: false

jobs:
  update-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7.0.0

      - name: Check for updates
        run: ./scripts/update_context.py

      - name: Get the current date
        id: date
        run: echo "current-date=$(date +'%Y-%m-%d')" >>"$GITHUB_OUTPUT"

      - name: Create a pull request
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/create-pull-request@v8
        with:
          branch: create-pull-request/check-update
          delete-branch: true
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: |
            chore: update document_type (${{ steps.date.outputs.current-date }})
          title: |
            [create-pull-request] chore: update document_type (${{ steps.date.outputs.current-date }})

  check-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: tueda/check-upstream-action-dev@main
        with:
          upstream-repository: tueda/cookiecutter-latex-makefile
          branch-token: ${{ secrets.CHECK_UPSTREAM_TOKEN }}
